# Generated by Django 5.2.7 on 2026-01-04 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='member',
            field=models.ForeignKey(limit_choices_to={'role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maingroup',
            name='delta',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Delta'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postbooking',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.maingroup'),
        ),
        migrations.AddField(
            model_name='postbooking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='code',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Code'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.maingroup'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.subgroup'),
        ),
        migrations.AddField(
            model_name='weeklypost',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.maingroup'),
        ),
        migrations.AddField(
            model_name='weeklypost',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postbooking',
            unique_together={('member', 'booking_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('member', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklypost',
            unique_together={('member', 'booking_date')},
        ),
    ]
